version: 2
jobs:
  plan:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /terraform/state
    steps:
      - checkout
      - run:
          name: Init
          command: terraform init -input=false
      - run:
          name: Plan
          command: terraform plan -destroy -input=false -out=tfplan -no-color
      - run:
          name: Render plan for PR comment
          command: terraform show -no-color tfplan > tfplan.txt
      - persist_to_workspace:
          root: /terraform/state
          paths:
            - .

  build1:
    working_directory: /terraform/state
    docker: 
      - image: hashicorp/terraform  

    steps:
      - checkout 
      - run:
          name: "init"
          command: terraform init

      - run:
          name: "plan"
          command: terraform plan   -input=false 
  
  build2:
    working_directory: /terraform/state
    docker: 
      - image: hashicorp/terraform  

    steps:
      - checkout 
      - run:
          name: "init"
          command: terraform init

      - run:
          name: "apply"
          command: terraform apply --auto-approve 
    
   
  destroy:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /terraform/state
    steps:
      - attach_workspace:
          at: /terraform/state
      - run:
          name: destroy
          command: terraform apply tfplan
  
workflows:
  version: 2
  plan_pr:
    jobs:
      - build1:
          context: GOOGLE_CREDENTIALS 
      
      - hold:
          type:  approval
      
      - build2:
          context: GOOGLE_CREDENTIALS 
          requires:
            - build1
            - hold
      
      - plan:
          context: GOOGLE_CREDENTIALS
          requires:
            - build2
      
      - approve_desroty1:
          type:  approval
          requires:
            - plan
      - approve_desroty2:
          type:  approval
          requires:
            - plan
       
      
      - destroy:
          context: GOOGLE_CREDENTIALS 
          requires:
            - plan
            - approve_desroty1
            - approve_desroty2
          
          