version: 2.1

jobs: 
  build:
    docker: 
      - image: hashicorp/terraform   # this terraform image to run our project 
    
    steps: 
      - checkout 
      - run:
          name: "init"
          command: terraform init
          context: $GOOGLE_GREDENTIALS 
      - run:
          name: "plan"
          command: terraform plan
          context: $GOOGLE_GREDENTIALS
      
  build2:
    docker: 
      - image: hashicorp/terraform   # this terraform image to run our project 
    steps:
      - checkout 
      - run:
          name: "init"
          command: terraform init 
          context: $GOOGLE_GREDENTIALS
      - run:
          name: "plan"
          command: terraform plan
          context: $GOOGLE_GREDENTIALS
      - run:
          name: "apply"
          command: terraform apply --auto-approve
          context: $GOOGLE_GREDENTIALS 
workflows: 
  build:
    jobs:
      - build
          
      - hold:
          type: approval 
          requires:
            - build
      - build2:
          
          requires: 
            - hold
            - build