version: 2.1

jobs: 
  build:
    docker: 
      - image: hashicorp/terraform    
    
    steps: 
      - checkout 
      - run:
          name: "init"
          command: terraform init
          
      - run:
          name: "plan"
          command: terraform plan
          
      
  build2:
    docker: 
      - image: hashicorp/terraform     
    steps:
      - checkout 
      - run:
          name: "init"
          command: terraform init 
          
      
          
      - run:
          name: "apply"
          command: terraform apply --auto-approve 
  destroy:
    docker:
      - image: hashicorp/terraform  
    steps:
      - run:
          name: "init"
          command: terraform init      
      - run:
          name: "destroy"
          command: terraform destroy --auto-approve     
workflows: 
  build:
    jobs:
      - build:
          context: GOOGLE_CREDENTIALS 
      - Attention When you will approve:
          type: approval 
          requires:
            - build
      - build2:
          context: GOOGLE_CREDENTIALS
          requires: 
            - Attention When you will approve
            - build
      - Pay attention to click  it will destroy :
          type: approval
          requires: 
            - Attention When you will approve
            - build
            - build2
      - Are you shure to destroy:
          type: approval
          requires: 
            - Attention When you will approve
            - build
            - build2 
      - destroy:
          context: GOOGLE_CREDENTIALS
          requires:
            - build
            - Pay attention to click  it will destroy
            - Are you shure to destroy
          