name: 'Terraform CI CD'

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  terraform_plan:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      ENVIRONMENTS: 'QA,DEV,SAT'   

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cronjob upgrade the ASG capacities
        # if: ${{ github.event_name == 'schedule' }}
        run: |
          for i in $(echo $ENVIRONMENTS | tr ',' ' '); do
            echo "Running for $i environment"     
            aws configure set aws_access_key_id ${{ secrets[format('TF_{0}_USER_AWS_KEY', $i)] }}
            echo $i
          done    
