name: 'Terraform CI CD'

on: 
  schedule:
   - cron: '* * * * *'
  workflow_dispatch:

  
 


jobs:
  terraform_plan:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      ENVIRONMENTS: 'QA,DEV,SAT'   

    steps:
      - name: Send some mail
        uses: wadeww/send-email-action@master
        with:
          server_address: smtp.gmail.com
          port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Workflow finished
          body: Job completed ${{job.status}}
          to: john@denver.com, elton@john.com
          from: Me
