name: 'Terraform CI CD'

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  terraform_plan:
    name: 'Terraform'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [QA, DEV, SAT]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cronjob upgrade the ASG capacities
        run: |
          echo "Running for ${{ matrix.environment }} environment"
          aws configure set aws_access_key_id ${{ secrets[format('TF_{0}_USER_AWS_KEY', matrix.environment)] }}
          # Your remaining steps here
  terraform_plan:
    name: 'Terraform'
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cronjob upgrade the ASG capacities
        run: |
          echo "Running for if workflow dispatch
