name: 'Terraform CI CD'

on: 
  schedule:
   - cron: '*/2 * * * *'
  workflow_dispatch:

  
 


jobs:
  terraform_plan:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      ENVIRONMENTS: 'QA,DEV,SAT'   

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cronjob upgrade the ASG capacities
        # if: ${{ github.event_name == 'schedule' }}
        run: |
          for ENVIRONMENT in $(echo $ENVIRONMENTS | tr ',' ' '); do
            echo "Running for $ENVIRONMENT environment"     
            echo $ENVIRONMENT
            done    

