name: 'Terraform CI CD'

on: 
  schedule:
   - cron: '0 20 * * 1-5'
   - cron: '* * * * *'
  workflow_dispatch:

  
 


jobs:
  terraform_plan:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      ENVIRONMENTS: 'QA,DEV,SAT'   

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: commands
        if: ${{ github.event_name == 'schedule' }}
        run: |
          echo one
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets[format('SECRET_{0}', $ENVIRONMENT)] }}
        run: |
          example-command "$SUPER_SECRET"         

