name: 'Terraform CI CD'

on: 
  schedule:
   - cron: '0 20 * * 1-5'
   - cron: '*/2 * * * *'
  workflow_dispatch:

  
 


jobs:
  terraform_plan:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      ENVIRONMENTS: 'QA,DEV,SAT'   

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cronjob upgrade the ASG capacities
        if: ${{ github.event_name == 'schedule' }}
        run: |
          for ENVIRONMENT in $(echo $ENVIRONMENTS | tr ',' ' '); do
            echo "Running for $ENVIRONMENT environment"
            aws configure set aws_access_key_id ${{ secrets[format('TF_{0}_USER_AWS_KEY', $ENVIRONMENT)] }}
            aws configure set aws_secret_access_key ${{ secrets[format('TF_{0}_USER_AWS_SECRET', $ENVIRONMENT)] }}
            aws configure set region eu-west-1     
            echo $ENVIRONMENT
            done    

