name: 'Terraform CI CD'

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  terraform_plan:
    name: 'Terraform'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [QA, DEV, SAT]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cronjob upgrade the ASG capacities
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets[format('TF_{0}_USER_AWS_KEY', matrix.environment)] }}
          aws-secret-access-key: ${{ secrets[format('TF_{0}_USER_AWS_SECRET', matrix.environment)] }}
          aws-region: eu-west-1
      - name:
        run: |
          echo "Running for ${{ matrix.environment }} environment"

  terraform_apply:
    name: 'Terraform'
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cronjob upgrade the ASG capacities
        run: |
          echo "Running for if workflow dispatch"
