name: Send Email

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENTS: 'QA,DEV,SAT'   

    steps:
      - name: Send some mail
        uses: wadeww/send-email-action@master
        with:
          server_address: email-smtp.us-east-1.amazonaws.com
          port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Workflow finished
          body: Job completed ${{job.status}}
          to: saitovbeknazar07@gmail.com 
          from: saitovbeknazar6@gmail.com 
