name: Send Email

on:
  push:
    branches:
      - main


jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3.9.0
        with:
          server_address: smtp.gmail.com
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Workflow ${{ job.status }} - Status: ${{ github.workflow }} ${{ github.sha }}"
          body: |
            Job completed successfully.

            Workflow Status: ${{ job.status }}

            Repository: ${{ github.repository }}
            Workflow: ${{ github.workflow }}
            Commit SHA: ${{ github.sha }}
            Action URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

          to: saitovbeknazar07@gmail.com
          from: saitovbeknazar6@gmail.com
          server_port: 465
